# Generated by Django 3.1.2 on 2021-09-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iraq', '0002_auto_20210918_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhod',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com/', max_length=255),
        ),
        migrations.AddField(
            model_name='people',
            name='facebook',
            field=models.URLField(default='www.facebook.com', max_length=255),
        ),
    ]
